import Header from "@/components/Header";
import "./globals.css";
import { ClerkProvider, ClerkLoading, ClerkLoaded } from "@clerk/nextjs";
import Loader from "@/components/Loader";

export const metadata = {
  title: "NextJS Authentication",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="max-w-screen-xl mx-auto">
          <ClerkLoading>
            <Loader></Loader>
          </ClerkLoading>
          <ClerkLoaded>
            <Header></Header>
            {children}
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
